version: "3"
services:
    product:
        build: .
        ports:
            - "5003:5003"
    redis:
        image: "redis:alpine"
        restart: always
        expose:
            - '6379'
        ports:
            - '6379:6379'
